name: Noir

on:
  push:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: noir-lang/noirup@v0.1.3
        with:
          toolchain: 0.19.2

      - name: Generate test cases
        run: |
          yarn install --immutable
          # Generates 10 random semaphore identities as test cases. 
          node ./scripts/generate_test_case.js 10

      - name: Run nargo test
        run: nargo test
